name: Test datasette-app-support plugin

on: [push]

jobs:
  test-plugin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8, 3.9]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions/cache@v2
      name: Configure pip caching
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        cd datasette-app-support && pip install -e '.[test]'
    - name: Run tests
      run: |
        cd datasette-app-support && pytest
    - name: Run Black
      run: |
        cd datasette-app-support && black . --check
